spring:
 mvc:
  view:
   prefix: /WEB-INF/jsp/
   suffix: .jsp
 jpa:
  database-platform: com.ms.sqlite.SQLiteDialect
  generate-ddl: true
  hibernate: 
   ddl-auto: update
 datasource:
  url: jdbc:sqlite:ms.db
  driver-class-name: org.sqlite.JDBC
server:
 port: 8888
 context-path: /test
